[tool.poetry]
package-mode = false
name = "caraml-examples"
version = "0.1.0"
description = "Example usages of caramlops tooling"
authors = []
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
caraml = { path = "../caraml/", develop = true }
torch = "^2.6.0"
pandas = "^2.2.3"
scipy = "^1.14.1"
tensorflow = "^2.18.0"
onnx = "^1.22.0"
onnxruntime = "^1.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
